gantt
    dateFormat  YYYY-MM-DD
    tickInterval 1week
    weekday monday
    excludes saturday,sunday

    section 1 этап
        Внедрение коробки    : 2024-10-01, 2d
        Подключение к SSO   : 2024-10-03, 5d
        Анализ и подготовка ТЗ : 2024-10-10, 7d
    
    section 2 этап
        API :2024-10-21, 5d
        Matomo :2024-10-28, 5d
        Редизайн :2024-11-04, 9.5d
        Стайл-гайд  :2024-11-18, 5d
        Воркфлоу    :2024-11-25, 16.5d
        Письма  :2024-12-16, 5d







