title: Автотест
logo: logo.svg
logo_dark: logo_dark.svg
group: products
order: 1
code: test
description: Для автотестирования
description_en: Autotests
style: blue
versions:
  - test*
  - Z
  - x
relatedLinks:
  - url: https://play.google.com/store/apps/details?id=ru.ics_it.quiz
    title: App in Google Play for Android
    icon: google-play
    iconPrefix: fab
terms:
  md:
    title: markdown
    summary: Markdown
    description: >-
      облегчённый *язык разметки*, созданный с целью написания наиболее
      читаемого и удобного для правки текста, но пригодного для преобразования в
      языки для продвинутых публикаций.
    url: https://ru.wikipedia.org/wiki/Markdown
sharePointDirectory: test
language: null
supportedLanguages: []
properties: []
