code: GX
title: Gramax Docs
logo: ./logo.svg
description: Для документации и хранения знаний.
group: products
style: black
relatedLinks:
  - url: https://t.me/gramax_chat
    title: Telegram-канал
    icon: mail-question
language: ru
supportedLanguages:
  - ru
  - en
