gantt
    dateFormat  YYYY-MM-DD
    tickInterval 1week
    weekday monday
    excludes saturday,sunday
    
    section 2 этап
        Создание библиотеки проверок :2024-09-02, 10d
        Создание песочницы :2024-09-16, 30d
        Интеграция в Gramax :2024-10-04, 20d

